# Generated by Django 5.1.3 on 2024-11-27 11:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('this_is_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryproduct',
            name='category_descr',
            field=models.TextField(default=django.utils.timezone.now, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoryproduct',
            name='category_photo',
            field=models.FileField(default=django.utils.timezone.now, upload_to='category_image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='pr_photo',
            field=models.FileField(upload_to='product_image'),
        ),
    ]
