# Generated by Django 5.1.3 on 2024-12-04 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('this_is_app', '0002_categoryproduct_category_descr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pr_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='this_is_app.product')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='this_is_app.usercart')),
            ],
            options={
                'verbose_name': 'Favorite',
                'verbose_name_plural': 'Favorites',
            },
        ),
    ]
