# Generated by Django 5.1.3 on 2024-12-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('this_is_app', '0003_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
