# Generated by Django 5.1.3 on 2024-12-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('this_is_app', '0004_alter_favorites_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=5)),
                ('svv', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Bank Cart',
                'verbose_name_plural': 'Bank Carts',
            },
        ),
    ]
