# Generated by Django 5.1.3 on 2024-12-06 11:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('this_is_app', '0006_alter_bankcart_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankcart',
            old_name='svv',
            new_name='cvv',
        ),
        migrations.AddField(
            model_name='bankcart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
